# Generated by Django 3.1.4 on 2021-10-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211002_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpoint',
            old_name='post_header',
            new_name='post_point_header',
        ),
    ]
